### ISSUE TITLE
Allow refusing

### ISSUE THREAD

**Issue by BenoitDuffez** [leblanc-simon/eu-cookie-law-bundle#2]
AFAIK the law forces us to 1/ inform, 2/ obtain consent and 3/ offer a way to refuse.

1/ and 2/ are covered, but not 3/.
I've seen somes site that put some kind of help message on how to disable cookies in the browser.

Do you think this would be a good idea?

**Comment by leblanc-simon** [comment]
I'm not sure it's a good idea. Cookies can be legite and don't require consent (cookies which not track people and are only for technical)

I would like implement two things :
* https://opt-out.ferank.eu : allow the users to choose what they want
* https://blog.eleven-labs.com/fr/google-analytics-et-le-bandeau-cookie-cnil/#le-javascript : automatic refuse if doNotTrack is use

Objective : 25 may because it's the legal date for GDPR
